In [1]:
#1 Create a vector of zeros of size 10 but have the fifth value be 1.
import numpy as np
np.set_printoptions(precision=3, threshold=10000, linewidth=80, suppress=True)
z = np.zeros(10)
z[4] = 1
z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [2]:
#2 Create a vector with values ranging from 10 to 49, inclusive.
beep = np.arange(10,50,1)
beep

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49])

In [67]:
#3 Write a function, reverse(x) which reverses a vector, so that the first element becomes the last element.
def reversearray(arr):
    """return a 1D vector with the elements reversed 
    Input: 
        x: 1D array 
    Output: 
        res: 1D array, with the elements of `x` reversed"""
    res = arr[::-1]
    return res

reversearray(beep)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [87]:
#4 Write a function find_nonzero(x) that finds the indices of non-zero elements

test = np.array([1,2,0,0,4,0])

def find_nonzero(x):
    """return the indices of non-zero elements of an array.

Input:      x:  array
Output:     indices: array of integer indices """
    
    indices= np.where(x!=0)
    return indices

find_nonzero(test)

(array([0, 1, 4]),)

In [76]:
#5 Create a 3x3x3 array with normally distributed (μ=0,σ=1) random values.

norm = np.random.normal(loc=0.0, scale=1.0, size=9)
normblock = norm.reshape(3,3)
normblock

array([[ 0.37225535,  1.43650164, -0.10321089],
       [-0.26127887,  0.70659627, -0.43751162],
       [-0.50216312,  0.61897105,  1.42756586]])

In [ ]:
#6 Create a 10x10 array with random values. Find the minimum value of the 2nd row and the maximum value of the 4th column
arr = np.random.rand(10,10)

print(arr.min(axis=1)[1]) ### minimum of 2nd row
print(arr.max(axis=0)[3]) ### maximum of 4th column

In [45]:
#7 Create a vector of size 10 with values ranging from 0 to 1, both excluded.
uwu = np.arange(0,1,1/11)
ugu = uwu[1:11]
print(ugu)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


In [64]:
#8 Create a random vector of size 10, then sort it.

tens = np.random.rand(10)
tens.sort()
tens

array([ 0.06693387,  0.22857389,  0.26201302,  0.33836282,  0.5243859 ,
        0.54917   ,  0.69977246,  0.81053672,  0.83908137,  0.91272965])

In [4]:
#9 Write a function is_equal(A, B) that compare two arrays A and B and checks to see if they are equal.

A = np.zeros(10).reshape(2,5)
B = np.zeros(10)

def is_equal(A,B):
    """"return True if two arrays are the same shape and all the elements are equal.

Inputs:
    A, B:  array
Output:
    Bool:  True if A and B have the same shape and identical elements. """""

    for i in range(0,len(A.flatten()),1):
        if A.flatten()[i] == B.flatten()[i]:  
            continue
        if not A.flatten()[i] == B.flatten()[i]:
            return False
    if A.shape == B.shape:
        return True
    else:
        return False

is_equal(A,B)

False

In [ ]:
#10 Subtract the row mean from rows of a matrix

a = np.random.rand(5,5)
amean = a.mean(axis=1)

print(a - amean)

In [197]:
#11
## Multiply arrays

a = np.random.rand(5,5,3)
b = np.random.rand(5,5)
c = np.random.rand(3,5,5)

## Multiply an array of dimension (5,5,3) with an array with dimensions (5,5). 

print(a*b[:,:,np.newaxis])

## Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).
print(c*b)

[[[ 0.375  0.36   0.347]
  [ 0.461  0.048  0.212]
  [ 0.325  0.366  0.831]
  [ 0.064  0.065  0.128]
  [ 0.209  0.213  0.225]]

 [[ 0.401  0.306  0.388]
  [ 0.364  0.163  0.001]
  [ 0.239  0.061  0.104]
  [ 0.448  0.785  0.92 ]
  [ 0.013  0.493  0.054]]

 [[ 0.011  0.06   0.055]
  [ 0.125  0.522  0.146]
  [ 0.209  0.063  0.024]
  [ 0.014  0.006  0.003]
  [ 0.012  0.179  0.152]]

 [[ 0.705  0.349  0.553]
  [ 0.078  0.155  0.417]
  [ 0.021  0.104  0.021]
  [ 0.526  0.104  0.51 ]
  [ 0.334  0.287  0.276]]

 [[ 0.204  0.137  0.365]
  [ 0.002  0.02   0.005]
  [ 0.222  0.06   0.143]
  [ 0.55   0.829  0.494]
  [ 0.339  0.063  0.055]]]
[[[ 0.044  0.377  0.661  0.08   0.072]
  [ 0.453  0.225  0.163  0.787  0.052]
  [ 0.055  0.349  0.088  0.005  0.123]
  [ 0.031  0.511  0.048  0.013  0.723]
  [ 0.378  0.017  0.012  0.707  0.441]]

 [[ 0.211  0.004  0.818  0.067  0.334]
  [ 0.127  0.378  0.29   0.363  0.67 ]
  [ 0.037  0.241  0.067  0.007  0.173]
  [ 0.763  0.097  0.145  0.006  0.646]
  [ 0.292  0

In [90]:
#12 Creating a new array
Z = np.arange(1,15,1)

R = np.arange(44).reshape(11,4)

for i in range(0,11,1):
    k=0
    karly = np.zeros(11)
    karly = Z[k+i:k+4+i]
    R[i,:]=karly
    
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [175]:
#12 Write a function cart2polar(xy) which takes in an Nx2 matrix of x, y pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix.

yz = np.array([4.,5.,8.,3.]).reshape(2,2)
xy = np.array([4.,5.,8.,3.,2.,3.]).reshape(3,2)


def cart2polar(xy):
    """Return equivalent polar coordinates of specified cartesian points.
    Inputs:
        xy: array
            Nx2 array of Cartesian coordinates, with columns x and y respectively.
    Returns: 
        rp: array 
            Nx2 array of polar coordinates, with columns radius and angle respectively"""
    rp = np.zeros_like((xy), dtype='float64')
    height = xy.shape[0]
    for i in range(0,height,1):
        r= np.sqrt([xy[i,0]**2 + xy[i,1]**2])
        theta= np.arctan([xy[i,1]/xy[i,0]])
        rp[i,0]= float(r)
        rp[i,1]= float(theta)
    return rp

cart2polar(xy)

array([[ 6.403,  0.896],
       [ 8.544,  0.359],
       [ 3.606,  0.983]])

In [32]:
%timeit np.arange(1024.0).reshape(4, 8, 16, 2)

## I'm tired and I can't figure out how to do it, but 
import time
t_start = time.time()
for n in range(0,2,1):
    for k in range(0,16,1):
        for j in range(0,8,1):
            for i in range(0,4,1):
                sol = np.arange().reshape(i,1,1,1) * [j,1,1,1] * [1,1,i,1] * [1,1,1,n]
t_stop = time.time()

## divide the first time by the 2nd to get a ratio.

The slowest run took 20.09 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 4.6 µs per loop


In [ ]:
%timeit b = np.random.rand(4, 8, 16, 2)

In [ ]:
%timeit sol = a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
#15 fix the code
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :] ## created array containing [:2,:] elements
    myint = 4  ## integer for operations
    ac = aa/myint ## divided array by 4
    a[:2, :] = aa - ac ### changed it so that 1/4 is subtracted from the corresponding elements in a, condensed
    return a*b[:,np.newaxis]   ### changed what the function returns so that a is multipled with a version of b with a new axis
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)


assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

In [198]:
#16 Calculate components of a vector

f = open('burl1h2010.txt')
f.seek(0)
wdir = []
wspd = []

for line in f.readlines():  
    data = line.split()
    if data[0] == '2010':
        wdir.append(float(data[5]))
        wspd.append(float(data[6]))
        
vdir = np.array(wdir)
vspd = np.array(wspd)

def components(vdir,vspd):
    """Take in vector and return components.

Inputs:
    vdir: vector direction in degrees
    vspd: vector magnitude

Returns:
    u: x component of vector
    v: y component of vector"""
    
    uo = list()
    vo = list()
    for i in range(0,len(vdir),1):
        x = vspd[i]*np.cos(vdir[i]*2*np.pi/360)
        uo.append(x)
        y = vspd[i]*np.sin(vdir[i]*2*np.pi/360)
        vo.append(y)
    u = np.array(uo)
    v = np.array(vo)
    return u,v
    

In [199]:
components(vdir,vspd)

(array([ -2.084,  -1.961,  -2.121,   1.455,   3.165,   1.754,   4.935,   8.693,
          8.267,  13.724,   9.372,   8.321,   9.976,  13.3  ,  14.   ,  12.27 ,
         10.013,  12.353,   8.894,  11.572,  10.294,  11.484,   8.579,  10.186,
          9.4  ,   8.18 ,  10.542,   8.453,   9.231,   8.174,   8.593,   8.983,
          7.935,   8.53 ,   9.149,   8.313,   7.64 ,   8.999,   6.797,   7.841,
          7.752,   8.051,   8.388,   7.967,   7.65 ,   7.659,   7.091,   7.139,
          6.235,   4.45 ,   3.475,   4.294,   4.665,   6.162,   7.113,   7.034,
          6.683,   6.385,   6.707,   8.131,   7.593,   7.029,   6.495,   8.747,
          6.206,   5.538,   4.467,   5.107,   4.756,   4.617,   5.827,   6.035,
          6.722,   6.303,   5.768,   5.155,   4.695,   6.904,   8.309,   7.948,
          6.784,   6.149,   7.011,   6.887,   6.259,   6.415,   8.053,   6.908,
          6.753,   6.027,   5.161,   5.942,   7.742,  11.485,  10.149,   9.227,
         11.753,  11.542,  10.766,  11.0

In [ ]:
#17 Write and use a class

import glob

class dataclass(object)

glob.glob(m10***.cnv2)

In [114]:
#18 Write a function that computes averages using a sliding window over a vector

def runningmean(vec,N):
    """Return the running average of a vector, with averaging window of size N.

Inputs:
    vec: Input vector
    N (int): Averaging window size, or number of elements to include in mean on either side of each element.

Outputs:
    out: Vector of running-averaged values; same size as vec"""
    
    if N == 0:
        return vec
    else:
        out = []
        for i in range(0,len(vec)-N,1):
                if i < N:
                    runner = np.mean(vec[:i+N+1])
                    out.append(runner)
                else:
                    runner = np.mean(vec[i-N:i+N+1])
                    out.append(runner)
        for i in range(len(vec)-N,len(vec),1):
                    runner = np.mean(vec[i-N:])
                    out.append(runner)
    return out
    
runit = np.array([1.,2.,3.,4.,5.])
runningmean(runit,1)

[1.5, 2.0, 3.0, 4.0, 4.5]