In [6]:
# Create a vector of zeros of size 10 but have the fifth value be 1.
import numpy as np
z = np.zeros(10)
z[4] = 1
z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [5]:
# Create a vector with values ranging from 10 to 49, inclusive.
beep = np.arange(10,50,1)
beep

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# Write a function, reverse(x) which reverses a vector, so that the first element becomes the last element.
def reversearray(arr):
    return arr[::-1]

reversearray(beep)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [46]:
# Write a function find_nonzero(x) that finds the indices of non-zero elements
#### how to do it for rows and columns?

test = [1,2,0,0,4,0]
test1 = np.array(test)

def find_nonzero(x):
    values = list()
    size = 1
    xflat = x.flatten()
    for dim in np.shape(x): size *= dim
    for i in range (0,size,1):
        if xflat[i] == 0:
            continue
        if xflat[i] > 0 or xflat[i] < 0:
            values.append(i)
    index = np.array(values)
    return index

find_nonzero(test1)

array([0, 1, 4])

10

In [49]:
# Create a 3x3x3 array with normally distributed (μ=0,σ=1) random values.

norm = np.random.normal(loc=0.0, scale=1.0, size=9)
normblock = norm.reshape(3,3)
normblock

array([[ 0.18538923, -1.05260134, -1.56948459],
       [-1.1353688 ,  0.17934741,  0.61044412],
       [-0.16396704, -0.269221  ,  2.37335218]])

In [83]:
#### Create a 10x10 array with random values. Find the minimum value of the 2nd row and the maximum value of the 4th column
arr = np.random.rand(10,10)

print(arr.min(axis=1)[1]) ### minimum of 2nd row
print(arr.max(axis=0)[3]) ### maximum of 4th column

0.119498688254
0.931430357095
[[ 0.35524746  0.10391301  0.34417506  0.39695678  0.2789731   0.21053625
   0.77763869  0.95597202  0.41603847  0.42844556]
 [ 0.58067809  0.61821165  0.80994339  0.29784805  0.90601371  0.76946712
   0.11949869  0.6252359   0.78828142  0.13492152]
 [ 0.72696591  0.68778356  0.95298065  0.93143036  0.18869318  0.04653309
   0.80311805  0.65057108  0.73143946  0.61393088]
 [ 0.23251151  0.620037    0.6058413   0.48628468  0.79210839  0.07858751
   0.50757058  0.77422036  0.82184659  0.22634703]
 [ 0.49927346  0.30317543  0.69859683  0.25991007  0.75669244  0.16172608
   0.77887141  0.79518627  0.29311228  0.09341342]
 [ 0.14738788  0.64452735  0.58582878  0.8781846   0.91195024  0.18382314
   0.56782316  0.28407328  0.53123035  0.69803122]
 [ 0.46593712  0.90775907  0.41980824  0.10801865  0.5154923   0.16264846
   0.2379609   0.02284248  0.19115761  0.71630201]
 [ 0.83640091  0.65952703  0.24329802  0.76420273  0.14702875  0.8738613
   0.82379383  0.95675

In [94]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded.
uwu = np.linspace(0.01,1,endpoint=False,num=10)
uwu

array([ 0.01 ,  0.109,  0.208,  0.307,  0.406,  0.505,  0.604,  0.703,
        0.802,  0.901])

In [97]:
# Create a random vector of size 10, then sort it.

tens = np.random.rand(10)
tens.sort()
tens


array([ 0.03326036,  0.07056612,  0.11780207,  0.15856935,  0.31565592,
        0.33055163,  0.6809892 ,  0.82767387,  0.93917088,  0.99799276])

In [ ]:
# Write a function is_equal(A, B) that compare two arrays A and B and checks to see if they are equal.

def is_equal(A,B):
    