In [2]:
# Create a vector of zeros of size 10 but have the fifth value be 1.
import numpy as np
z = np.zeros(10)
z[4] = 1
z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [3]:
# Create a vector with values ranging from 10 to 49, inclusive.
beep = np.arange(10,50,1)
beep

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [67]:
# Write a function, reverse(x) which reverses a vector, so that the first element becomes the last element.
def reversearray(arr):
    "return a 1D vector with the elements reversed \n Input: \n x: 1D array \n Output: \n res: 1D array, with the elements of `x` reversed"
    return arr[::-1]

reversearray(beep)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [5]:
# Write a function find_nonzero(x) that finds the indices of non-zero elements
#### how to do it for rows and columns?

test = [1,2,0,0,4,0]
test1 = np.array(test)

def find_nonzero(x):
    values = list()
    size = 1
    xflat = x.flatten()
    for dim in np.shape(x): size *= dim
    for i in range (0,size,1):
        if xflat[i] == 0:
            continue
        if xflat[i] > 0 or xflat[i] < 0:
            values.append(i)
    index = np.array(values)
    return index

find_nonzero(test1)

array([0, 1, 4])

In [6]:
# Create a 3x3x3 array with normally distributed (μ=0,σ=1) random values.

norm = np.random.normal(loc=0.0, scale=1.0, size=9)
normblock = norm.reshape(3,3)
normblock

array([[-0.91076202,  0.55657692,  0.87184228],
       [-0.26492313,  0.12354973,  0.61517846],
       [ 0.96650216,  1.07773364,  1.24671886]])

In [7]:
#### Create a 10x10 array with random values. Find the minimum value of the 2nd row and the maximum value of the 4th column
arr = np.random.rand(10,10)

print(arr.min(axis=1)[1]) ### minimum of 2nd row
print(arr.max(axis=0)[3]) ### maximum of 4th column

0.115090471288
0.947296746967


In [68]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded.
uwu = np.arange(0,1,1/11)
ugu = uwu[1:11]
print(ugu)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


In [9]:
# Create a random vector of size 10, then sort it.

tens = np.random.rand(10)
tens.sort()
tens


array([ 0.09752454,  0.19610913,  0.23624302,  0.25947239,  0.71106529,
        0.82806944,  0.85041497,  0.85991535,  0.86473522,  0.91590253])

In [59]:
# Write a function is_equal(A, B) that compare two arrays A and B and checks to see if they are equal.

def is_equal(A,B):
    if A.shape == B.shape:
        return True
    else:
        return False

True

In [71]:
## Subtract the row mean from rows of a matrix

a = np.random.rand(5,5)
amean = a.mean(axis=1)

print(a - amean)

[[-0.02430833 -0.52591649 -0.63506617 -0.3391533  -0.51213495]
 [-0.11640075  0.35214993 -0.09358372  0.18484308 -0.01814254]
 [ 0.54110063  0.35434837 -0.30965122  0.25366286 -0.04357579]
 [ 0.84647354  0.13500595  0.05600028  0.0261169  -0.22872554]
 [ 0.42511825 -0.04992103  0.05034155 -0.08719754 -0.24138397]]


In [78]:
## Multiply arrays

a = np.random.rand(5,5,3)
b = np.random.rand(5,5)
c = np.random.rand(3,5,5)

## Multiply an array of dimension (5,5,3) with an array with dimensions (5,5). 

print(a*b[:,:,np.newaxis])

## Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).
print(c*b)

[[[  2.55268920e-01   2.46865791e-01   2.57078596e-01]
  [  4.91628070e-01   1.45824475e-02   5.87549019e-01]
  [  4.18838440e-02   1.29084768e-01   1.87373322e-01]
  [  1.92072755e-01   3.77909982e-01   3.66182450e-01]
  [  7.23376919e-03   2.95527765e-03   1.78045814e-02]]

 [[  1.00763041e-02   5.97988441e-02   5.46718135e-03]
  [  3.77572509e-01   7.97825739e-01   1.67550906e-01]
  [  1.85864393e-02   2.16156946e-01   5.83565350e-02]
  [  2.78428330e-01   1.92022146e-01   1.87395458e-01]
  [  2.05256217e-01   1.46988627e-01   3.17443223e-01]]

 [[  2.41494562e-01   4.45895784e-01   5.34666175e-01]
  [  2.97021983e-01   4.04769818e-01   5.76821150e-02]
  [  1.69388373e-01   3.43308121e-02   1.72885304e-01]
  [  2.28140890e-02   3.40904138e-01   3.61100218e-01]
  [  2.05725194e-01   2.39507166e-01   2.99187508e-01]]

 [[  4.68059700e-01   9.79041078e-02   3.94176763e-01]
  [  4.91630604e-04   1.14161955e-03   7.40803171e-05]
  [  2.41419048e-01   9.19117581e-01   8.04894934e-01]
  [ 

array([[[ 1.86535546,  1.80395032,  0.3757159 ],
        [ 3.30189481,  0.0979393 ,  0.78922469],
        [ 1.09380078,  3.37106164,  0.97865461],
        [ 1.42904821,  2.81170322,  0.54488975],
        [ 0.88111024,  0.359968  ,  0.43373789]],

       [[ 0.1139242 ,  0.67609468,  0.01236255],
        [ 2.04446269,  4.32003104,  0.18144943],
        [ 0.42149588,  4.90192124,  0.26467726],
        [ 4.07744787,  2.8120712 ,  0.54886312],
        [ 1.87191191,  1.34051853,  0.57900877]],

       [[ 1.42235959,  2.62624608,  0.62981755],
        [ 3.25425459,  4.43476952,  0.12639623],
        [ 1.85391377,  0.37574223,  0.37843736],
        [ 0.21725011,  3.24630369,  0.68772469],
        [ 2.35045194,  2.7364178 ,  0.68365555]],

       [[ 3.34279938,  0.69921378,  0.56302811],
        [ 2.11549028,  4.91239774,  0.06375364],
        [ 1.30633518,  4.97340886,  0.87106844],
        [ 1.64836182,  4.00113924,  0.88183328],
        [ 2.06958141,  0.04607754,  0.0588101 ]],

       [[ 0.

In [45]:
## Creating a new array
Z = np.arange(1,15,1)

R = np.arange(44).reshape(11,4)

for i in range(0,11,1):
    k=0
    karly = np.zeros(11)
    karly = Z[k+i:k+4+i]
    R[i,:]=karly
    
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [152]:
## Write a function cart2polar(xy) which takes in an Nx2 matrix of x, y pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix.

yz = np.array([4.,5.,8.,3.]).reshape(2,2)


def cart2polar(xy):
    "Return equivalent polar coordinates of specified cartesian points. \nInputs:\nxy: array\nNx2 array of Cartesian coordinates, with columns x and y respectively.\n Returns: \n rp: array \n Nx2 array of polar coordinates, with columns radius and angle respectively"
    rp = np.zeros_like(xy)
    r = np.sqrt([xy[0,0]**2 + xy[0,1]**2,xy[1,0]**2 + xy[1,1]**2])
    theta = np.arctan([xy[0,1]/xy[0,0],xy[1,1]/xy[1,0]])
    rp[:,0] = r
    rp[:,1] = theta
    return rp

cart2polar(yz)

array([[ 6.40312424,  0.89605538],
       [ 8.54400375,  0.35877067]])

In [153]:
%timeit np.arange(1024.0).reshape(4, 8, 16, 2)


The slowest run took 483.48 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 4.98 µs per loop


In [105]:
%timeit b = np.random.rand(4, 8, 16, 2)

array([ 6.,  8.])

In [106]:
%timeit sol = a * b

array([ 6.40312424,  8.54400375])

In [161]:
for i in range(0,1025,256):
    fours = list()
    fours.append(float(i))
    fours.array 

In [176]:
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :] ## created flattened array containing [:2,:] elements
    myint = 4  ## myint for operations
    ac = aa/myint ## created array ac that is 1/4 of the value of aa
    ad = a - ac ### changed this line so that the subtracting 1/4 operation works, condensed
    return ad*b.reshape(1,3)   ### changed what the function returns
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)


assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [190]:
aa = a[:2, :] ## created flattened array containing [:2,:] elements
myint = 4  ## myint for operations
ac = aa/myint ## created array ac that is 1/4 of the value of aa
a[:2, :] = aa - ac ### changed this line so that the subtracting 1/4 operation works, condensed



array([ 3.,  3.,  3.])